"""Final Agent H artifact schemas."""

from datetime import datetime, timezone
from typing import Dict, List

from pydantic import BaseModel, Field

from schemas.common import Severity
from schemas.finding import Finding


class FinalFindingsResult(BaseModel):
    """Merged, deduplicated, severity-sorted finding output from Agent H."""

    run_id: str = Field(..., description="Unique identifier for this pipeline run.")
    overall_severity: Severity = Field(
        ..., description="Highest severity across final findings."
    )
    findings: List[Finding] = Field(
        default_factory=list,
        description="Final merged findings sorted by severity.",
    )
    total_findings: int = Field(..., description="Number of final findings.")
    requires_human_review: bool = Field(
        ..., description="Whether the final result needs human review."
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when Agent H finalized findings.",
    )


class PipelineMetrics(BaseModel):
    """Run-level metrics written by Agent H."""

    run_id: str = Field(..., description="Unique identifier for this pipeline run.")
    status: str = Field(..., description="Final pipeline status.")
    duration_seconds: float = Field(
        ..., ge=0.0, description="End-to-end processing duration in seconds."
    )
    extraction_clause_count: int = Field(
        ..., ge=0, description="Number of extracted clauses."
    )
    validation_finding_count: int = Field(
        ..., ge=0, description="Number of findings from Agent D."
    )
    risk_finding_count: int = Field(
        ..., ge=0, description="Number of findings from Agent E."
    )
    counterparty_exception_count: int = Field(
        ..., ge=0, description="Number of counterparty exceptions from Agent C."
    )
    final_finding_count: int = Field(
        ..., ge=0, description="Number of final merged findings."
    )
    obligation_count: int = Field(
        ..., ge=0, description="Number of obligation records exported."
    )
    fallback_assisted: bool = Field(
        ..., description="Whether extraction used the synthetic fallback."
    )
    exception_rate: float = Field(
        ..., ge=0.0, description="Final findings divided by extracted clauses."
    )
    overall_severity: Severity = Field(
        ..., description="Highest final finding severity."
    )
    artifact_paths: Dict[str, str] = Field(
        default_factory=dict,
        description="Run artifacts generated by the pipeline.",
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when metrics were generated.",
    )
